---
sidebar: sidebar 
permalink: about/whats-new.html 
keywords: whats new, enhancements, new features 
summary: NetAppでは、自動化ソリューション、製品REST API、関連ソフトウェアを定期的に更新して、新機能や機能拡張、バグ修正を提供しています。 
---
= NetApp自動化の最新情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppでは、自動化ソリューション、製品REST API、関連ソフトウェアを定期的に更新して、新機能や機能拡張、バグ修正を提供しています。



== 2023年7月27日

.Cloud Volumes ONTAP
Cloud Volumes ONTAPのサポートは、パブリッククラウド環境によって編成されています。以下のクラウド環境向けの新しいソリューションが提供されます。

* link:../solutions/cvo-gcp-burst-to-cloud.html["Cloud Volumes ONTAP for Google Cloud -クラウドへのバースト"]




== 2023年6月4日

その https://console.netapp.com/automationHub["NetApp Console自動化ハブ"^] コンソールの Web ユーザー インターフェイスから利用できます。自動化ハブは、 NetApp製品の自動導入と統合に役立つソリューションへのアクセスを提供します。これらのソリューションのドキュメントは、以下に示すように、いくつかの異なる製品または機能領域に分類されています。

.Amazon FSx for NetApp ONTAP管理
次の 2 つのAmazon FSx for NetApp ONTAP管理ソリューションが提供されます。

* link:../solutions/fsxn-burst-to-cloud.html["Amazon FSx for NetApp ONTAP管理 - クラウドへのバースト"]
* link:../solutions/fsxn-disaster-recovery.html["Amazon FSx for NetApp ONTAP管理 - 災害復旧"]


.Azure NetApp Files
Azure NetApp Filesを使用したOracleの導入を支援するソリューションが含まれています。

* link:../solutions/anf-oracle.html["Azure NetApp Filesを使用したOracle"]


.Cloud Volumes ONTAP
Cloud Volumes ONTAPのサポートは、パブリッククラウド環境によって編成されています。初期のソリューションは次の2つのクラウド環境で提供されます。

* link:../solutions/cvo-aws-burst-to-cloud.html["Cloud Volumes ONTAP AWS -クラウドへのバースト"]
* link:../solutions/cvo-azure-burst-to-cloud.html["Cloud Volumes ONTAP Azure -クラウドへのバースト"]

