---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation catalog, automation catalog, overview, introduction 
summary: NetAppコンソール自動化カタログは、 NetApp の顧客、パートナー、従業員が利用できる自動化ソリューションのコレクションです。カタログにはいくつかの機能と利点があります。 
---
= NetAppコンソール自動化カタログの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppコンソール自動化カタログは、 NetApp の顧客、パートナー、従業員が利用できる自動化ソリューションのコレクションです。カタログにはいくつかの機能と利点があります。

単一の場所で自動化のニーズに対応:: アクセスできます https://console.netapp.com/automationCatalog["NetAppコンソール自動化カタログ"^]コンソールの Web ユーザー インターフェイスを介して。これにより、 NetApp製品とサービスの自動化と運用を強化するために必要なスクリプト、プレイブック、モジュールが 1 か所に集まります。
ソリューションはNetAppによって作成、テストされています。:: すべての自動化ソリューションとスクリプトは、NetAppによって作成、テストされています。各ソリューションは、特定のお客様のユースケースまたは要求を対象としています。最も重点が置かれているのは、NetAppのファイルサービスやデータサービスとの統合です。
ドキュメント:: 各自動化ソリューションには、開始するのに役立つ関連ドキュメントが含まれています。ソリューションにはコンソールの Web インターフェイスからアクセスしますが、すべてのドキュメントはこのサイトから入手できます。ドキュメントは、 NetApp製品とクラウド サービスに基づいて構成されています。
将来を見据えた強固な基盤:: NetApp は、お客様のデータセンターとクラウド環境の自動化の改善と合理化を支援することに尽力しています。当社は、顧客の要件、テクノロジーの変化、継続的な製品統合に対応するために、コンソール自動化カタログを継続的に強化していく予定です。
皆様の貴重なご意見をぜひお聞かせください:: NetAppカスタマーエクスペリエンスオフィス（CXO）自動化チームが、皆様からのご意見をお待ちしています。フィードバック、問題、機能のリクエストについては、mailto：ng-cxo-automation-admins@cxo automation-admins@cxo NetApp .com [CXO automation team]までEメールでお問い合わせください。

