---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation catalog, automation catalog, overview, introduction 
summary: BlueXP  自動化カタログは、NetAppのお客様、パートナー様、従業員が利用できる自動化ソリューションのコレクションです。カタログには、いくつかの機能と利点があります。 
---
= BlueXP  自動化カタログの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  自動化カタログは、NetAppのお客様、パートナー様、従業員が利用できる自動化ソリューションのコレクションです。カタログには、いくつかの機能と利点があります。

単一の場所で自動化のニーズに対応:: には、BlueXP  Webユーザインターフェイスからアクセスできます https://console.bluexp.netapp.com/automationCatalog["BlueXP自動化カタログ"^]。これにより、NetApp製品およびサービスの自動化と運用を強化するために必要なスクリプト、プレイブック、およびモジュールを1箇所で管理できます。
ソリューションはNetAppによって作成、テストされています。:: すべての自動化ソリューションとスクリプトは、NetAppによって作成、テストされています。各ソリューションは、特定のお客様のユースケースまたは要求を対象としています。最も重点が置かれているのは、NetAppのファイルサービスやデータサービスとの統合です。
ドキュメント:: 各自動化ソリューションには、作業を開始するのに役立つ関連ドキュメントが含まれています。これらのソリューションにはBlueXP  のWebインターフェイスからアクセスできますが、すべてのドキュメントはこのサイトで入手できます。ドキュメントは、NetApp製品とクラウドサービスに基づいて構成されています。
将来を見据えた強固な基盤:: NetAppは、お客様がデータセンターとクラウド環境の自動化を改善、合理化できるよう支援することをお約束します。お客様の要件、テクノロジの変更、および継続的な製品統合に対応するために、BlueXP  自動化カタログを継続的に強化していく予定です。
皆様の貴重なご意見をぜひお聞かせください:: NetAppカスタマーエクスペリエンスオフィス（CXO）自動化チームが、皆様からのご意見をお待ちしています。フィードバック、問題、機能のリクエストについては、mailto：ng-cxo-automation-admins@cxo automation-admins@cxo NetApp .com [CXO automation team]までEメールでお問い合わせください。

